demo:
  before_script:
    - pip install lxml
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="/root/.local/bin:$PATH"
    - poetry config virtualenvs.in-project true # for caching
    - poetry install --no-interaction --no-ansi
  tags:
    - ins-student
  image: python:3.9
  script: poetry run netaut --help
  cache:
    - key: "project-${CI_JOB_NAME}-py3.9"
      paths:
      - .cache/pip
      - .venv
    - key: "project-${CI_JOB_NAME}-yang"
      paths:
      - yang
