stages:
  - build
  - test
  - deploy

variables:
  PYTHON_VERSION: "3.9"
  POD_NUMBER: 8

cache:
  key: "project-${CI_JOB_NAME}-py3.9"
  paths:
    - .cache/pip
    - yang

before_script:
  - pip install lxml
  - curl -sSL https://install.python-poetry.org | python3 -
  - export PATH="/root/.local/bin:$PATH"
  - poetry config virtualenvs.in-project true
  - poetry install --no-interaction --no-ansi
  - source .venv/bin/activate

test_poetry:
  stage: build
  image: python:$PYTHON_VERSION
  script:
    - poetry run netaut --help
  artifacts:
    paths:
      - .venv/

test_connection:
  stage: test
  image: appropriate/curl:latest
  script:
    - nc -zv sw01-pod-$POD_NUMBER.network.garden 830 -w5
    - nc -zv sw02-pod-$POD_NUMBER.network.garden 830 -w5
    - nc -zv sw03-pod-$POD_NUMBER.network.garden 830 -w5
    - nc -zv sw04-pod-$POD_NUMBER.network.garden 830 -w5

#test_commands:
#  stage: test
#  image: python:$PYTHON_VERSION
#  script:
#    - poetry run netaut --pod-number $POD_NUMBER get-config

deploy:
  stage: deploy
  image: python:$PYTHON_VERSION
  script:
    - poetry run netaut deploy
  environment: 
    name: production
  only:
    - master
  when: manual