stages:
  - build
  - test
  - deploy

variables:
  PYTHON_VERSION: "3.9"

cache:
  key: "project-${CI_JOB_NAME}-py3.9"
  paths:
    - .cache/pip
    - .venv
    - yang

build:
  stage: build
  image: python:$PYTHON_VERSION
  before_script:
    - pip install lxml
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="/root/.local/bin:$PATH"
    - poetry config virtualenvs.in-project true
    - poetry install --no-interaction --no-ansi
  script:
    - poetry run netaut --help
  only:
    - develop
    - feature/*

test:
  stage: test
  image: python:$PYTHON_VERSION
  script:
    - poetry run netaut validate
    - poetry run netaut get-config
  only:
    - develop
    - feature/*

deploy:
  stage: deploy
  image: python:$PYTHON_VERSION
  script:
    - poetry run netaut deploy
  environment: 
    name: production
  only:
    - master
  when: manual