---
iosxe:
  username: ins
  platform: iosxe
  port: 830
  connection_options:
    netconf:
      extras:
        hostkey_verify: false
        timeout: 300
        allow_agent: false
        look_for_keys: false